ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr
ARDUINO_PORT  = /dev/ttyACM*
BOARD_TAG     = uno
AVRDUDE_ARD_BAUDRATE = 115200
AVRDUDE_CONF = /etc/avrdude.conf


include /usr/share/arduino/Arduino.mk